package com.flandre.notebook;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.speech.tts.TextToSpeech;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Native phone learning flows; cloud login is optional for all local features. */
final class NotebookScreens implements AutoCloseable {
    final MainActivity a;
    Runnable back;
    String search="",subject="",filter="",kind="",difficulty="",sort="",wordSearch="",wordFilter="";
    int libraryOffset=0,wordOffset=0;
    final List<FormulaView> formulas=new ArrayList<>();
    TextToSpeech speech;boolean speechReady=false;
    DeepSeekLogin webLogin;final DeepSeekPow webPow;
    static final int BACKUP_SAVE=20,BACKUP_OPEN=21,JSON_SAVE=22,JSON_OPEN=23,WORDS_OPEN=24,CSV_SAVE=25;
    interface Action {void run() throws Exception;}
    NotebookScreens(MainActivity activity){a=activity;webPow=new DeepSeekPow(activity);}
    void safe(Action action){try{action.run();}catch(Exception e){a.status(e instanceof IOException?e.getMessage():"内容格式有误，原题库与草稿已保留。");}}
    void page(String title,String hint,Runnable goBack){if(webLogin!=null){webLogin.destroy();webLogin=null;}for(FormulaView v:formulas){v.stopLoading();v.destroy();}formulas.clear();a.location="notebook";back=goBack;a.screen(title,hint);}
    void back(){if(back!=null)back.run();else a.home();}
    public void close(){webPow.close();if(webLogin!=null){webLogin.destroy();webLogin=null;}for(FormulaView v:formulas){v.stopLoading();v.destroy();}formulas.clear();if(speech!=null)speech.shutdown();}
    String ask(JSONObject profile,String instruction,String text,byte[] image) throws Exception {return profile.optString("provider").equals("deepseek_web")?new DeepSeekWeb(webPow).ask(profile,instruction,text,image):AiClient.ask(profile,instruction,text,image);}
    String workspaceName(){return a.book.uid.equals("LOCAL")?"本机题库":a.getPreferences(0).getString("username","账号题库")+(a.api==null?" · 离线":"");}
    EditText field(String label,String value,boolean multiline){a.text(label,14,true);EditText e=a.edit(label,false);e.setText(value);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(20000)});if(multiline){e.setSingleLine(false);e.setMinLines(3);e.setMaxLines(8);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setGravity(Gravity.TOP);e.setLayoutParams(new LinearLayout.LayoutParams(-1,-2));}return e;}
    void watch(EditText e,Runnable changed){e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){}public void afterTextChanged(Editable value){if(!a.busy)changed.run();}});}
    FormulaView math(String text){LinearLayout card=a.ui.card(PhoneUi.SURFACE);FormulaView view=new FormulaView(a,text);card.addView(view,new LinearLayout.LayoutParams(-1,a.dp(80)));formulas.add(view);return view;}
    int goal(){try{return Math.max(1,Math.min(500,Integer.parseInt(a.book.state("daily_goal","10"))));}catch(Exception e){return 10;}}
    void goalSettings(Runnable done){EditText e=new EditText(a);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setText(Integer.toString(goal()));AlertDialog dialog=new AlertDialog.Builder(a).setTitle("每日题目练习目标").setMessage("每天 1～500 次。完成并记录作答后计入目标。").setView(e).setNegativeButton("取消",null).setPositiveButton("保存",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(b->safe(()->{int value=Integer.parseInt(e.getText().toString());if(value<1||value>500){e.setError("请填写 1～500");return;}a.book.putState("daily_goal",Integer.toString(value));dialog.dismiss();done.run();})));dialog.show();}
    void home(){safe(()->{
        page("Flandre 错题本","",null);a.location="home";a.ui.navigation("home");
        List<JSONObject> all=a.book.entries("","","");JSONObject stats=a.book.statistics();int due=a.book.entries("","","due").size(),drafts=a.book.drafts().length();
        a.ui.studyHero(stats.getInt("today"),goal(),new java.text.SimpleDateFormat("M 月 d 日 · EEEE",Locale.CHINA).format(new Date())+"  /  "+workspaceName(),()->goalSettings(this::home));a.primary("拍照识题",a::camera);
        a.ui.metrics(new String[]{count(all.size()),count(due),count(stats.getInt("today"))},new String[]{"已收录","待复习","今日练习"});
        a.ui.section("快速收录","");a.ui.shortcuts(new String[]{"相册选题","手动录题","英语单词"},new String[]{"image","edit","words"},new Runnable[]{a::pick,()->safe(()->newDraft(null)),this::wordList});
        a.ui.section("接着学","");if(!a.book.state("practice","").isEmpty())a.ui.row("继续上次练习","上次作答和学习进度已保留","learn",()->safe(this::practicePage));
        a.ui.row(due>0?"有 "+due+" 道题等你复习":"练习与复习",all.isEmpty()?"收录第一道题，开始自己的学习记录":"按掌握程度复习，也可以自选题目练习","learn",all.isEmpty()?this::captureHome:this::practiceMenu);
        if(drafts>0)a.ui.row("继续整理草稿","还有 "+drafts+" 份待核对内容","draft",this::draftList);a.ui.row("查看学习统计","了解练习次数与自己的作答情况","stats",this::statistics);
    });}
    boolean getCompactWidth(){return a.getResources().getConfiguration().screenWidthDp<360;}
    String count(int n){return n>=10000?String.format(Locale.CHINA,"%.1f万",n/10000.0):Integer.toString(n);}
    void captureHome(){page("收录错题","先拍下来，再一步步整理。",a::home);a.ui.navigation("capture");a.ui.empty("让纸上的题目留在身边","保留原图与裁剪区域，识题结果由你核对后收录。","camera");a.primary("拍照识题",a::camera);a.ui.row("从相册选题","选择已有照片，框选题目区域","image",a::pick);a.ui.row("手动录入题目","题干、答案和笔记都可以直接编辑","edit",()->safe(()->newDraft(null)));a.ui.section("已保存的内容","");a.ui.row("继续整理草稿","查看还未核对收录的题目","draft",this::draftList);}
    void mine(){safe(()->{page("我的","",a::home);a.ui.navigation("mine");LinearLayout profile=a.ui.card(PhoneUi.SOFT);profile.addView(a.ui.label(workspaceName(),23,PhoneUi.TEXT,true));a.ui.space(profile,8);profile.addView(a.ui.label(a.book.uid.equals("LOCAL")?"离线也能整理、练习和复习。登录后可与电脑同步。":a.api==null?"题库已保存在手机。同步时重新登录即可。":"题库保存在手机，可手动同步到其他设备。",14,PhoneUi.MUTED,false));a.ui.section("账号与学习","");a.ui.row("账号与同步",a.api==null?"登录、切换账号与题目同步":"查看同步状态与冲突题目","cloud",this::account);a.ui.row("学习统计","查看作答记录和每日练习情况","stats",this::statistics);a.ui.row("英语单词本","翻卡、拼写与英语发音","words",this::wordList);a.ui.section("应用设置","");a.ui.row("手机识题模型","DeepSeek 网页版或自定义模型服务","settings",this::modelSettings);a.ui.row("设置与备份","复习间隔、导入导出和完整备份","backup",this::settings);a.text("Flandre  ·  "+a.getPackageManager().getPackageInfo(a.getPackageName(),0).versionName,12,false);});}
    void library(String query,String category,String mode){search=query;subject=category;filter=mode;kind="";difficulty="";sort="";libraryOffset=0;libraryPage();}
    List<JSONObject> libraryRows() throws Exception {List<JSONObject> rows=a.book.entries(search,subject,filter);Iterator<JSONObject> it=rows.iterator();while(it.hasNext()){JSONObject q=it.next().getJSONObject("payload").getJSONObject("question");if(!kind.isEmpty()&&!kind.equals(q.optString("question_type"))||!difficulty.isEmpty()&&!difficulty.equals(q.optString("difficulty")))it.remove();}if(!sort.isEmpty())Collections.sort(rows,(l,r)->{JSONObject lr=l.optJSONObject("payload").optJSONObject("review"),rr=r.optJSONObject("payload").optJSONObject("review");String key=sort.equals("due")?"due_at":"last_reviewed_at",lv=lr==null?"":lr.optString(key),rv=rr==null?"":rr.optString(key);return sort.equals("due")?(lv.isEmpty()?"9999":lv).compareTo(rv.isEmpty()?"9999":rv):rv.compareTo(lv);});return rows;}
    void advancedFilters(){safe(()->{LinearLayout box=a.ui.vertical();box.setPadding(a.dp(20),0,a.dp(20),a.dp(12));List<String> types=new ArrayList<>();types.add("全部题型");for(JSONObject e:a.book.entries("","","")){String value=e.getJSONObject("payload").getJSONObject("question").optString("question_type");if(!value.isEmpty()&&!types.contains(value))types.add(value);}String[][] labels={types.toArray(new String[0]),{"全部难度","简单","中等","困难"},{"最近收录","优先到期","最近练习"}};List<Spinner> controls=new ArrayList<>();int[] indices={Math.max(0,types.indexOf(kind)),Arrays.asList("","简单","中等","困难").indexOf(difficulty),Arrays.asList("","due","recent").indexOf(sort)};for(int i=0;i<labels.length;i++){box.addView(a.ui.label(new String[]{"题型","难度","排序"}[i],14,PhoneUi.MUTED,true));Spinner s=new Spinner(a);s.setAdapter(a.ui.choices(Arrays.asList(labels[i])));s.setSelection(Math.max(0,indices[i]));box.addView(a.ui.dropdown(s),new LinearLayout.LayoutParams(-1,a.dp(52)));controls.add(s);a.ui.space(box,12);}new AlertDialog.Builder(a).setTitle("更多筛选").setView(box).setNegativeButton("取消",null).setNeutralButton("重置",(d,w)->{kind="";difficulty="";sort="";libraryOffset=0;libraryPage();}).setPositiveButton("应用",(d,w)->{kind=controls.get(0).getSelectedItemPosition()==0?"":types.get(controls.get(0).getSelectedItemPosition());difficulty=new String[]{"","简单","中等","困难"}[controls.get(1).getSelectedItemPosition()];sort=new String[]{"","due","recent"}[controls.get(2).getSelectedItemPosition()];libraryOffset=0;libraryPage();}).show();});}
    void libraryPage(){safe(()->{
        page("我的题库","搜索题干、笔记、标签、知识点和来源。",a::home);
        a.ui.navigation("library");
        EditText q=a.edit("搜索题干、笔记和标签",false);q.setText(search);List<String> subjects=new ArrayList<>();subjects.add("全部学科");for(JSONObject row:a.book.entries("","","")){String s=row.getJSONObject("payload").getJSONObject("question").optString("subject");if(!s.isEmpty()&&!subjects.contains(s))subjects.add(s);}Spinner cat=new Spinner(a);cat.setAdapter(a.ui.choices(subjects));cat.setSelection(subjects.indexOf(subject)<0?0:subjects.indexOf(subject));
        String[] modes={"全部题目","错题","到期复习","已掌握","不确定","未掌握","同步冲突"},codes={"","wrong","due","mastered","unsure","unknown","conflict"};Spinner state=new Spinner(a);state.setAdapter(a.ui.choices(Arrays.asList(modes)));state.setSelection(Arrays.asList(codes).indexOf(filter)<0?0:Arrays.asList(codes).indexOf(filter));LinearLayout filters=new LinearLayout(a);filters.addView(a.ui.dropdown(cat),new LinearLayout.LayoutParams(0,a.dp(52),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,a.dp(52),1);sp.leftMargin=a.dp(10);filters.addView(a.ui.dropdown(state),sp);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,-2);fp.topMargin=a.dp(8);a.page.addView(filters,fp);
        LinearLayout actions=new LinearLayout(a);Button apply=a.button("筛选",()->{search=q.getText().toString();subject=cat.getSelectedItemPosition()==0?"":subjects.get(cat.getSelectedItemPosition());filter=codes[state.getSelectedItemPosition()];libraryOffset=0;libraryPage();}),add=a.primary("新增题目",()->safe(()->newDraft(null)));a.page.removeView(apply);a.page.removeView(add);actions.addView(apply,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,-2,1);ap.leftMargin=a.dp(10);actions.addView(add,ap);LinearLayout.LayoutParams act=new LinearLayout.LayoutParams(-1,-2);act.topMargin=a.dp(10);a.page.addView(actions,act);q.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);q.setOnEditorActionListener((v,id,event)->{if(id==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){apply.performClick();return true;}return false;});
        a.button("更多筛选"+(kind.isEmpty()&&difficulty.isEmpty()&&sort.isEmpty()?"":" · 已应用"),this::advancedFilters);List<JSONObject> rows=libraryRows();a.ui.section("我的题目",rows.size()+" 道");
        if(rows.isEmpty())a.ui.empty(search.isEmpty()&&subject.isEmpty()&&filter.isEmpty()&&kind.isEmpty()&&difficulty.isEmpty()?"还没有收录题目":"没有找到匹配题目",search.isEmpty()&&subject.isEmpty()&&filter.isEmpty()&&kind.isEmpty()&&difficulty.isEmpty()?"拍照、选图或手动添加，建立自己的错题本。":"试试更换关键词，或放宽学科与状态筛选。","library");
        for(int i=libraryOffset;i<Math.min(rows.size(),libraryOffset+40);i++){JSONObject e=rows.get(i),p=e.getJSONObject("payload"),question=p.getJSONObject("question");String stem=question.optString("stem");JSONObject review=p.optJSONObject("review");String hint=(question.optInt("is_wrong")==1?"错题 · ":"")+(question.optString("subject").isEmpty()?"未分类":question.optString("subject"))+(review==null?" · 未练习":" · "+masteryLabel(review.optString("mastery")))+(question.optString("difficulty").isEmpty()?"":" · "+question.optString("difficulty"))+(e.isNull("conflict")?"":" · 同步冲突");a.ui.question(hint,stem,()->detail(e.optString("id")));}
        if(libraryOffset>0)a.button("上一页",()->{libraryOffset=Math.max(0,libraryOffset-40);libraryPage();});if(libraryOffset+40<rows.size())a.button("下一页",()->{libraryOffset+=40;libraryPage();});
        if(!rows.isEmpty()){
            a.primary("练习筛选出的题目",()->safe(()->startPractice(rows)));
            FrameLayout more=new FrameLayout(a);more.setBackground(a.ui.ripple(PhoneUi.BG,14,false));more.setContentDescription("题目导出与打印");more.setFocusable(true);more.addView(a.ui.new Icon("more",PhoneUi.TEXT),new FrameLayout.LayoutParams(a.dp(22),a.dp(22),Gravity.CENTER));a.ui.bar.addView(more,new LinearLayout.LayoutParams(a.dp(48),a.dp(48)));
            Runnable print=()->{if(rows.size()>200){a.status("每次打印最多 200 道题，请缩小筛选范围。");return;}StringBuilder text=new StringBuilder();int n=0;for(JSONObject row:rows){JSONObject item=row.optJSONObject("payload").optJSONObject("question");text.append(++n).append(". ").append(questionText(item)).append("\n\n");}if(text.length()>500000){a.status("本次题目文本较多，请缩小打印范围。");return;}page("打印题目","通过系统打印选择保存为 PDF。",this::libraryPage);FormulaView view=math(text.toString());a.button("打印／保存 PDF",()->view.print("Flandre 题目"));a.button("返回题库",this::libraryPage);};
            more.setOnClickListener(v->{if(a.busy)return;PopupMenu menu=new PopupMenu(a,more);menu.getMenu().add(0,1,0,"导出 JSON");menu.getMenu().add(0,2,1,"导出 CSV");menu.getMenu().add(0,3,2,"打印／保存 PDF");menu.setOnMenuItemClickListener(item->{if(a.busy)return true;if(item.getItemId()==1)safe(()->exportJson());else if(item.getItemId()==2)safe(()->exportCsv());else print.run();return true;});menu.show();});
        }
    });}
    static String questionText(JSONObject q){StringBuilder s=new StringBuilder(q.optString("stem"));JSONObject opts=q.optJSONObject("options");if(opts!=null){List<String> keys=new ArrayList<>();Iterator<String> it=opts.keys();while(it.hasNext())keys.add(it.next());Collections.sort(keys);for(String k:keys)s.append("\n").append(k).append(". ").append(opts.optString(k));}return s.toString();}
    static String metadata(JSONObject q,String... keys){List<String> values=new ArrayList<>();for(String key:keys){String value=q.optString(key).trim();if(!value.isEmpty())values.add(value);}return android.text.TextUtils.join(" · ",values);}
    void detail(String id){safe(()->{
        JSONObject entry=a.book.entry(id);if(entry==null||entry.getInt("deleted")!=0){libraryPage();a.status("题目已删除。");return;}JSONObject p=entry.getJSONObject("payload"),q=p.getJSONObject("question");
        page("题目详情",metadata(q,"subject","question_type","grade","source"),this::libraryPage);a.ui.section("题目",q.optString("difficulty"));math(questionText(q));
        a.primary("查看答案与解析",()->{page("答案与解析","核对答案后再安排复习。",()->detail(id));a.ui.section("参考答案","");math(q.optString("answer").isEmpty()?"暂未填写答案":q.optString("answer"));a.ui.section("解题过程","");math(q.optString("explanation").isEmpty()?"暂未填写解析":q.optString("explanation"));a.button("返回题目",()->detail(id));});
        if(!q.optString("notes").isEmpty()){a.ui.section("我的笔记","");math(q.optString("notes"));}
        String labels=metadata(q,"tags","knowledge_points");if(!labels.isEmpty())a.text(labels,14,false);
        JSONObject review=p.optJSONObject("review");a.ui.row(review==null?"还没有练习记录":masteryLabel(review.optString("mastery")),review==null?"从这道题开始，记录掌握情况":"下次复习："+review.optString("due_at"),"learn",()->safe(()->startPractice(Collections.singletonList(entry))));
        a.button("编辑题目与笔记",()->safe(()->newDraft(entry)));a.button("练习这道题",()->safe(()->startPractice(Collections.singletonList(entry))));
        JSONArray images=p.getJSONArray("attachments");if(images.length()>0)a.button("查看原图（"+images.length()+" 张）",()->images(id,images));a.button("作答历史",()->safe(()->{page("作答历史","最近 100 次练习",()->detail(id));JSONArray h=a.book.history(id);for(int i=0;i<h.length();i++){JSONObject row=h.getJSONObject(i);a.text(row.optString("time")+" · "+(row.optInt("correct")==1?"答对":"答错")+" · "+masteryLabel(row.optString("mastery"))+"\n我的答案："+row.optString("answer"),15,false);}a.button("返回题目",()->detail(id));}));
        if(!entry.isNull("conflict"))a.button("处理同步冲突",()->conflict(id));
        a.button("删除题目",()->new AlertDialog.Builder(a).setTitle("删除这道题？").setMessage("同步后会同时删除账号云端题目。可先在设置中导出备份。").setNegativeButton("保留",null).setPositiveButton("删除",(dialog,which)->safe(()->{a.book.delete(id);libraryPage();})).show());a.button("返回题库",this::libraryPage);
    });}
    void showImage(JSONObject image){safe(()->{File file=a.book.file(image);byte[] bytes=CloudApi.read(file,CloudApi.MAX_IMAGE);if(!CloudApi.sha(bytes).equals(image.getString("sha256")))throw new IOException("原图校验失败，请从备份恢复。");BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);int sample=1;while(Math.max(bounds.outWidth,bounds.outHeight)/sample>2400)sample*=2;BitmapFactory.Options opts=new BitmapFactory.Options();opts.inSampleSize=sample;Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,opts);if(bitmap==null)throw new IOException("原图无法解码。");ImageView v=new ImageView(a);v.setImageBitmap(bitmap);v.setAdjustViewBounds(true);a.page.addView(v,new LinearLayout.LayoutParams(-1,-2));a.text(image.optString("original_name"),13,false);});}
    void images(String id,JSONArray images){imagePage(id,images,0);}
    void imagePage(String id,JSONArray images,int index){safe(()->{page("原图 "+(index+1)+" / "+images.length(),"保留的原图和裁剪图，可在题目中核对。",()->detail(id));showImage(images.getJSONObject(index));if(index>0)a.button("上一张",()->imagePage(id,images,index-1));if(index+1<images.length())a.button("下一张",()->imagePage(id,images,index+1));a.button("返回题目",()->detail(id));});}
    static String masteryLabel(String value){return value.equals("mastered")?"已掌握":value.equals("unsure")?"不确定":"未掌握";}
    void conflict(String id){safe(()->{JSONObject e=a.book.entry(id),remote=e.getJSONObject("conflict");page("同步冲突","两端修改不同，自动同步已暂停此题。本机版本会保留为草稿副本。",()->detail(id));a.text("本机内容",16,true);math(e.getJSONObject("payload").getJSONObject("question").optString("stem"));a.text("云端内容",16,true);if(remote.length()==0||remote.optBoolean("deleted"))a.text("云端记录已删除或不存在；保留本机会另存为新题。",15,false);else math(remote.getJSONObject("payload").getJSONObject("question").optString("stem"));a.button("保留本机修改",()->safe(()->{a.book.resolve(id,true);libraryPage();}));a.button("使用云端版本",()->safe(()->{a.book.resolve(id,false);libraryPage();}));a.button("稍后处理",()->detail(id));});}
    void newDraft(JSONObject entry) throws Exception {
        String id=CloudApi.id();JSONObject draft=new JSONObject().put("label",entry==null?"手动录题":"编辑题目").put("questions",new JSONArray().put(entry==null?new JSONObject():entry.getJSONObject("payload").getJSONObject("question"))).put("images",entry==null?new JSONArray():entry.getJSONObject("payload").getJSONArray("attachments"));if(entry!=null)draft.put("edit_id",entry.getString("id")).put("edit_revision",entry.getLong("revision"));a.book.draft(id,draft);editor(id,0);
    }
    String photoDraft(Notebook owner,byte[] original,String ext,byte[] cropped,String name,String note) throws Exception {
        String id=CloudApi.id();JSONArray images=new JSONArray().put(owner.addImage(original,ext,name+"-原图."+ext,id).put("role","original")).put(owner.addImage(cropped,"jpg",name+"-裁剪.jpg",id).put("role","crop"));
        owner.draft(id,new JSONObject().put("label",name).put("note",note).put("images",images).put("questions",new JSONArray()).put("raw",""));return id;
    }
    void draftList(){safe(()->{page("待整理草稿","未完成的内容都在这里，随时继续核对。",a::home);JSONArray list=a.book.drafts();for(int i=0;i<list.length();i++){JSONObject row=list.getJSONObject(i);String id=row.getString("id");a.button(row.getJSONObject("payload").optString("label","待整理题目"),()->draftPage(id));}if(list.length()==0)a.text("暂无未完成草稿。",16,false);a.button("返回首页",a::home);});}
    void draftPage(String id){safe(()->{JSONObject draft=a.book.draft(id);if(draft==null){draftList();return;}JSONArray questions=draft.optJSONArray("questions");if(questions!=null&&questions.length()>0){editor(id,0);return;}
        page("照片草稿",draft.optString("label")+"\n可在手机识题，也可粘贴已有的识题文字。",this::draftList);JSONArray images=draft.optJSONArray("images");if(images!=null&&images.length()>0)showImage(images.getJSONObject(images.length()-1));
        EditText raw=field("已有文字／模型原始响应",draft.optString("raw"),true);raw.setFilters(new InputFilter[]{new InputFilter.LengthFilter(2*1024*1024)});watch(raw,()->safe(()->{JSONObject d=a.book.draft(id);if(d!=null){d.put("raw",raw.getText().toString());a.book.draft(id,d);}}));
        if(images!=null&&images.length()>0)a.primary("开始手机 AI 识题",()->safe(()->{Notebook owner=a.book;JSONObject profile=ModelProfile.read(a,owner.uid);JSONObject image=images.getJSONObject(images.length()-1);byte[] data=CloudApi.read(owner.file(image),CloudApi.MAX_IMAGE);a.run(()->{String response=ask(profile,AiClient.RECOGNITION,"请按要求识别并解答整张题目图片。只返回 questions JSON。备注："+draft.optString("note"),data);JSONObject d=owner.draft(id);if(d==null)throw new IOException("草稿已不存在。");d.put("raw",response);owner.draft(id,d);try{d.put("questions",AiClient.parse(response));}catch(Exception invalid){d.put("parse_error",invalid instanceof IOException?invalid.getMessage():"模型未返回可核对的草稿，请查看原始响应。");}owner.draft(id,d);return id;},value->draftPage(id));}));
        if(!draft.optString("parse_error").isEmpty())a.status(draft.getString("parse_error"));a.button("从文字恢复草稿",()->safe(()->{JSONArray qs=AiClient.parse(raw.getText().toString());JSONObject d=a.book.draft(id);d.put("questions",qs).put("raw",raw.getText().toString());a.book.draft(id,d);editor(id,0);}));
        a.button("手动整理这张照片",()->safe(()->{JSONObject d=a.book.draft(id);d.put("questions",new JSONArray().put(new JSONObject()));a.book.draft(id,d);editor(id,0);}));a.button("模型设置",this::modelSettings);a.button("返回草稿列表",this::draftList);
    });}
    static JSONObject options(String text) throws Exception {
        JSONObject result=new JSONObject();String last=null;for(String line:text.split("\\n")){if(line.trim().isEmpty())continue;java.util.regex.Matcher m=java.util.regex.Pattern.compile("^\\s*([A-Z])\\s*[.、:：)]\\s*(.*)$").matcher(line);if(m.matches()){last=m.group(1);if(result.has(last))throw new IOException("选项标号重复。");result.put(last,m.group(2));}else if(last!=null)result.put(last,result.getString(last)+"\n"+line);else throw new IOException("选项请按 A. 内容、B. 内容，每项一行填写。");}return result;
    }
    void editor(String id,int index){safe(()->{
        JSONObject d=a.book.draft(id);if(d==null){draftList();return;}JSONArray questions=d.getJSONArray("questions");JSONObject question=questions.getJSONObject(index);
        page("核对题目 "+(index+1)+" / "+questions.length(),"修改自动保存在草稿中；确认收录后才进入题库。",this::draftList);
        Map<String,EditText> edits=new LinkedHashMap<>();String[] labels={"题干","学科","题型","标准答案","解析","标签","知识点","难度（简单／中等／困难）","来源","年级","个人笔记"};
        for(int i=0;i<Notebook.FIELDS.length;i++){String k=Notebook.FIELDS[i];edits.put(k,field(labels[i],question.optString(k),Arrays.asList("stem","answer","explanation","notes").contains(k)));}
        JSONObject opts=question.optJSONObject("options");StringBuilder text=new StringBuilder();if(opts!=null){Iterator<String> it=opts.keys();while(it.hasNext()){String k=it.next();text.append(k).append(". ").append(opts.optString(k)).append('\n');}}
        EditText optionEdit=field("选项（A. 内容，每项一行；非选择题留空）",d.optString("options_text_"+index,text.toString()),true);CheckBox wrong=new CheckBox(a);wrong.setText("标记为错题");wrong.setChecked(question.optInt("is_wrong",1)==1);a.page.addView(wrong);
        Runnable saveDraft=()->safe(()->{JSONObject current=a.book.draft(id);if(current==null)return;JSONObject q=current.getJSONArray("questions").getJSONObject(index);for(Map.Entry<String,EditText> item:edits.entrySet())q.put(item.getKey(),item.getValue().getText().toString());q.put("is_wrong",wrong.isChecked()?1:0);current.put("options_text_"+index,optionEdit.getText().toString());try{q.put("options",options(optionEdit.getText().toString()));current.remove("option_error_"+index);}catch(IOException error){current.put("option_error_"+index,error.getMessage());}a.book.draft(id,current);});
        for(EditText edit:edits.values())watch(edit,saveDraft);watch(optionEdit,saveDraft);wrong.setOnCheckedChangeListener((b,checked)->saveDraft.run());
        a.button("预览公式与内容",()->{saveDraft.run();safe(()->{JSONObject q=a.book.draft(id).getJSONArray("questions").getJSONObject(index);page("题目预览","预览不会自动收录。",()->editor(id,index));math(questionText(q)+"\n\n答案："+q.optString("answer")+"\n\n解析："+q.optString("explanation")+"\n\n笔记："+q.optString("notes"));a.button("返回编辑",()->editor(id,index));});});
        if(index>0)a.button("上一道草稿",()->{saveDraft.run();editor(id,index-1);});if(index+1<questions.length())a.button("下一道草稿",()->{saveDraft.run();editor(id,index+1);});
        a.primary(d.has("edit_id")?"保存题目修改":"确认收录全部草稿",()->{saveDraft.run();safe(()->{
            JSONObject current=a.book.draft(id);for(int i=0;i<current.getJSONArray("questions").length();i++)if(current.has("option_error_"+i))throw new IOException("第 "+(i+1)+" 道草稿的选项有误，请先修改。");
            if(current.has("edit_id")){JSONObject old=a.book.entry(current.getString("edit_id"));if(old==null||old.getInt("deleted")!=0||old.getLong("revision")!=current.getLong("edit_revision"))throw new IOException("题目已在其他页面更新；草稿保留，请核对新版本后另存。");
                a.book.db.beginTransaction();try{a.book.save(current.getString("edit_id"),current.getJSONArray("questions").getJSONObject(0),null);a.book.discardDraft(id);a.book.db.setTransactionSuccessful();}finally{a.book.db.endTransaction();}detail(current.getString("edit_id"));
            }else{List<String> ids=a.book.confirmDraft(id);libraryPage();a.status("已收录 "+ids.size()+" 道题，联网后可手动同步。");}
        });});
        if(d.has("edit_id"))a.button("将草稿另存为新题",()->{saveDraft.run();safe(()->{JSONObject current=a.book.draft(id);current.remove("edit_id");current.remove("edit_revision");a.book.draft(id,current);editor(id,index);});});
        if(!d.optString("raw").isEmpty())a.button("查看原始识题文字",()->new AlertDialog.Builder(a).setTitle("原始响应").setMessage(d.optString("raw")).setPositiveButton("关闭",null).show());
        a.button("返回草稿列表",this::draftList);a.button("舍弃草稿",()->new AlertDialog.Builder(a).setTitle("舍弃这份草稿？").setMessage("已收录的正式题目不受影响。").setNegativeButton("继续整理",null).setPositiveButton("舍弃",(dialog,which)->{a.book.discardDraft(id);draftList();}).show());
    });}
    void practiceMenu(){safe(()->{page("练习与复习","按自己的节奏练习，让每道错题慢慢变熟悉。",a::home);a.ui.navigation("learn");int all=a.book.entries("","","").size(),wrong=a.book.entries("","","wrong").size(),due=a.book.entries("","","due").size();a.ui.metrics(new String[]{count(all),count(wrong),count(due)},new String[]{"题库总数","错题","到期复习"});a.ui.section("题目练习","");if(!a.book.state("practice","").isEmpty())a.ui.row("继续上次练习","从上次保存的作答进度继续","learn",()->safe(this::practicePage),PhoneUi.SOFT);a.ui.row("练习全部题目",all+" 道题 · 支持顺序或随机练习","library",()->safe(()->startPractice(a.book.entries("","",""))));a.ui.row("只练错题",wrong+" 道错题 · 重点巩固","edit",()->safe(()->startPractice(a.book.entries("","","wrong"))));a.ui.row("复习到期题目",due+" 道题 · 按掌握情况安排","check",()->safe(()->startPractice(a.book.entries("","","due"))));a.ui.row("练习顺序",a.book.state("practice_order","ordered").equals("random")?"随机顺序 · 新练习生效":"按题库顺序 · 新练习生效","settings",()->new AlertDialog.Builder(a).setTitle("新练习的出题顺序").setSingleChoiceItems(new String[]{"按题库顺序","随机顺序"},a.book.state("practice_order","ordered").equals("random")?1:0,(d,w)->{a.book.putState("practice_order",w==1?"random":"ordered");d.dismiss();practiceMenu();}).setNegativeButton("取消",null).show());a.ui.section("英语与记录","");a.ui.row("英语单词本","翻卡学习、拼写练习和英语发音","words",this::wordList);a.ui.row("学习统计","查看自己的练习次数与作答情况","stats",this::statistics);});}
    void startPractice(List<JSONObject> rows) throws Exception {if(rows.isEmpty())throw new IOException("当前范围没有题目。");rows=new ArrayList<>(rows);if(a.book.state("practice_order","ordered").equals("random"))Collections.shuffle(rows);JSONArray ids=new JSONArray();for(JSONObject r:rows)ids.put(r.getString("id"));JSONObject p=new JSONObject().put("ids",ids).put("index",0).put("answer","").put("submitted",false).put("token",CloudApi.id());a.book.putState("practice",p.toString());practicePage();}
    void practicePage() throws Exception {
        String saved=a.book.state("practice","");if(saved.isEmpty()){practiceMenu();return;}JSONObject p=new JSONObject(saved);JSONArray ids=p.getJSONArray("ids");int index=p.getInt("index");if(index>=ids.length()){a.book.putState("practice","");page("练习完成","已保存作答记录和下次复习时间。",this::practiceMenu);a.button("查看学习统计",this::statistics);a.button("返回首页",a::home);return;}
        String id=ids.getString(index);JSONObject e=a.book.entry(id);if(e==null||e.getInt("deleted")!=0){p.put("index",index+1).put("answer","").put("submitted",false).put("token",CloudApi.id());p.remove("correct");p.remove("wrong");a.book.putState("practice",p.toString());practicePage();return;}
        JSONObject q=e.getJSONObject("payload").getJSONObject("question");page("练习 "+(index+1)+" / "+ids.length(),q.optString("subject")+" · "+q.optString("question_type"),this::practiceMenu);a.ui.studyProgress(index,ids.length());a.ui.section("本题题目","");math(questionText(q));
        boolean submitted=p.optBoolean("submitted");JSONObject options=q.getJSONObject("options");EditText answer=field("我的答案",p.optString("answer"),true);answer.setEnabled(!submitted);watch(answer,()->safe(()->{p.put("answer",answer.getText().toString());a.book.putState("practice",p.toString());}));
        if(options.length()>0&&!submitted){boolean multi=q.optString("question_type").contains("多选");if(multi){List<CheckBox> choices=new ArrayList<>();Iterator<String> keys=options.keys();while(keys.hasNext()){String k=keys.next();CheckBox c=new CheckBox(a);c.setText(k);a.ui.toggle(c);c.setChecked(p.optString("answer").contains(k));a.page.addView(c);choices.add(c);c.setOnCheckedChangeListener((b,v)->{StringBuilder value=new StringBuilder();for(CheckBox selected:choices)if(selected.isChecked())value.append(selected.getText());answer.setText(value.toString());});}}else{RadioGroup group=new RadioGroup(a);a.page.addView(group);Iterator<String> keys=options.keys();while(keys.hasNext()){String k=keys.next();RadioButton b=new RadioButton(a);b.setId(View.generateViewId());b.setText(k);a.ui.toggle(b);group.addView(b);if(k.equals(p.optString("answer")))b.setChecked(true);}group.setOnCheckedChangeListener((g,checked)->{RadioButton chosen=g.findViewById(checked);if(chosen!=null)answer.setText(chosen.getText());});}}
        if(!submitted){a.primary("提交并查看答案",()->safe(()->{p.put("answer",answer.getText().toString()).put("submitted",true);a.book.putState("practice",p.toString());practicePage();}));a.button("稍后继续",this::practiceMenu);return;}
        a.ui.section("参考答案","");math(q.optString("answer").isEmpty()?"暂未填写答案":q.optString("answer"));a.ui.section("解题过程","");math(q.optString("explanation").isEmpty()?"暂未填写解析":q.optString("explanation"));if(!q.optString("notes").isEmpty()){a.ui.section("个人笔记","");math(q.optString("notes"));}
        String standard=q.optString("answer").replaceAll("[\\s,，、]","").toUpperCase(Locale.ROOT),given=p.optString("answer").replaceAll("[\\s,，、]","").toUpperCase(Locale.ROOT);boolean objective=options.length()>0&&standard.matches("[A-Z]{1,12}");for(char c:standard.toCharArray())if(!options.has(Character.toString(c)))objective=false;
        boolean initial=p.has("correct")?p.optBoolean("correct"):objective&&letters(standard).equals(letters(given));CheckBox correct=new CheckBox(a);correct.setText(objective?"本题答对了（已自动对照选项，可调整）":"我对照参考答案，认为答对了");correct.setChecked(initial);a.ui.toggle(correct);a.page.addView(correct);CheckBox wrong=new CheckBox(a);wrong.setText("保留为错题，继续巩固");wrong.setChecked(p.has("wrong")?p.optBoolean("wrong"):!initial);a.ui.toggle(wrong);a.page.addView(wrong);correct.setOnCheckedChangeListener((b,v)->safe(()->{p.put("correct",v);a.book.putState("practice",p.toString());}));wrong.setOnCheckedChangeListener((b,v)->safe(()->{p.put("wrong",v);a.book.putState("practice",p.toString());}));
        a.ui.section("这道题，你掌握了吗？","记录后继续");for(String mastery:new String[]{"unknown","unsure","mastered"})a.button(masteryLabel(mastery)+" · 记录并继续",()->safe(()->{JSONObject next=Notebook.copy(p).put("index",index+1).put("answer","").put("submitted",false).put("token",CloudApi.id());next.remove("correct");next.remove("wrong");a.book.practiceOnce(id,p.optString("answer"),correct.isChecked(),wrong.isChecked(),mastery,days(mastery),p.getString("token"),next);practicePage();}));a.button("稍后继续",this::practiceMenu);
    }
    static Set<Character> letters(String s){Set<Character> set=new TreeSet<>();for(char c:s.toCharArray())set.add(c);return set;}
    int days(String mastery){try{int n=Integer.parseInt(a.book.state("days_"+mastery,mastery.equals("mastered")?"7":mastery.equals("unsure")?"3":"1"));return n>=0&&n<=365?n:1;}catch(Exception e){return 1;}}
    void statistics(){safe(()->{
        JSONObject stats=a.book.statistics();page("学习统计","看见自己的积累，保持自己的节奏。",this::practiceMenu);int total=stats.getInt("total");a.ui.studyHero(stats.getInt("today"),goal(),"学习记录 / "+workspaceName(),()->goalSettings(this::statistics));a.ui.metrics(new String[]{count(total),total==0?"—":Math.round(stats.getInt("correct")*100.0/total)+"%",count(stats.getInt("today"))},new String[]{"累计练习","正确率","今日练习"});
        JSONArray days=stats.getJSONArray("days");String[] names=new String[7];int[] counts=new int[7];Calendar date=Calendar.getInstance();date.add(Calendar.DATE,-6);java.text.SimpleDateFormat key=new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT),label=new java.text.SimpleDateFormat("M/d",Locale.ROOT);for(int i=0;i<7;i++){String day=key.format(date.getTime());names[i]=label.format(date.getTime());for(int j=0;j<days.length();j++)if(day.equals(days.getJSONObject(j).optString("day")))counts[i]=days.getJSONObject(j).optInt("count");date.add(Calendar.DATE,1);}a.ui.weekChart(names,counts);
        a.ui.section("题库概况","");a.ui.metrics(new String[]{count(a.book.entries("","","").size()),count(a.book.entries("","","wrong").size()),count(a.book.entries("","","due").size())},new String[]{"题目","错题","待复习"});a.ui.section("最近学习日","");if(days.length()==0)a.ui.empty("从第一组练习开始","完成作答后，这里会展示你的学习记录。","stats");else for(int i=0;i<days.length();i++){JSONObject day=days.getJSONObject(i);LinearLayout card=a.ui.card(PhoneUi.SURFACE);card.addView(a.ui.label(day.optString("day"),14,PhoneUi.MUTED,false));card.addView(a.ui.label(day.optInt("count")+" 次练习",18,PhoneUi.TEXT,true));}
    });}
    JSONArray filteredWords() throws Exception {JSONArray result=new JSONArray(),all=a.book.words();String query=wordSearch.trim().toLowerCase(Locale.ROOT);for(int i=0;i<all.length();i++){JSONObject w=all.getJSONObject(i);if(wordFilter.equals("due")&&w.optString("due_at").compareTo(Notebook.now())>0)continue;if(Arrays.asList("unknown","unsure","mastered").contains(wordFilter)&&!wordFilter.equals(w.optString("mastery")))continue;String text=w.optString("word")+"\n"+w.optString("meaning")+"\n"+w.optString("example");if(!query.isEmpty()&&!text.toLowerCase(Locale.ROOT).contains(query))continue;result.put(w);}return result;}

    void wordList(){safe(()->{
        page("英语单词本","每天记一点，慢慢变熟悉。",this::practiceMenu);JSONArray all=a.book.words();int due=0,mastered=0;for(int i=0;i<all.length();i++){JSONObject w=all.getJSONObject(i);if(w.optString("due_at").compareTo(Notebook.now())<=0)due++;if(w.optString("mastery").equals("mastered"))mastered++;}a.ui.metrics(new String[]{count(all.length()),count(due),count(mastered)},new String[]{"全部单词","待复习","已掌握"});if(!a.book.state("word_session","").isEmpty())a.ui.row("继续上次单词学习","你的翻卡和拼写进度已保留","words",()->safe(this::resumeWords),PhoneUi.SOFT);
        a.ui.shortcuts(new String[]{"翻卡学习","拼写练习","添加单词"},new String[]{"words","edit","plus"},new Runnable[]{()->safe(()->startWords(false)),()->safe(()->startWords(true)),()->wordEdit(null)});a.ui.row("AI 补全单词","生成释义与例句，核对后保存","learn",this::wordAI);a.ui.row("导入单词 TXT","每行一个词，可附上释义","backup",()->choose(WORDS_OPEN,"text/*",false));
        a.ui.section("我的单词","");EditText query=a.edit("搜索单词、释义和例句",false);query.setText(wordSearch);String[] labels={"全部单词","到期复习","未掌握","不确定","已掌握"},codes={"","due","unknown","unsure","mastered"};Spinner filter=new Spinner(a);filter.setAdapter(a.ui.choices(Arrays.asList(labels)));filter.setSelection(Math.max(0,Arrays.asList(codes).indexOf(wordFilter)));a.page.addView(a.ui.dropdown(filter),new LinearLayout.LayoutParams(-1,a.dp(52)));Button apply=a.button("筛选单词",()->{wordSearch=query.getText().toString();wordFilter=codes[filter.getSelectedItemPosition()];wordOffset=0;wordList();});query.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);query.setOnEditorActionListener((v,id,event)->{if(id==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){apply.performClick();return true;}return false;});JSONArray words=filteredWords();a.text("匹配 "+words.length()+" 个 · 翻卡与拼写使用当前范围",12,false);if(wordOffset>=words.length())wordOffset=0;
        if(words.length()==0)a.ui.empty("这里暂时没有单词","可以更换筛选，或添加、导入一些新单词。","words");for(int i=wordOffset;i<Math.min(words.length(),wordOffset+40);i++){JSONObject w=words.getJSONObject(i);a.ui.row(w.getString("word"),masteryLabel(w.optString("mastery"))+" · "+w.optString("meaning"),"words",()->wordEdit(w));}if(wordOffset>0)a.button("上一页单词",()->{wordOffset=Math.max(0,wordOffset-40);wordList();});if(wordOffset+40<words.length())a.button("下一页单词",()->{wordOffset+=40;wordList();});
    });}

    void wordEdit(JSONObject word){safe(()->{page(word==null?"添加单词":"编辑单词","单词、释义、音标和例句。",this::wordList);EditText w=field("单词／短语",word==null?"":word.optString("word"),false),meaning=field("释义",word==null?"":word.optString("meaning"),true),phonetic=field("音标",word==null?"":word.optString("phonetic"),false),example=field("例句与译文",word==null?"":word.optString("example"),true);a.primary("保存单词",()->safe(()->{a.book.word(word==null?null:word.getString("id"),w.getText().toString(),meaning.getText().toString(),phonetic.getText().toString(),example.getText().toString());wordList();}));if(word!=null){a.button("朗读单词",()->speak(w.getText().toString()));a.button("删除单词",()->new AlertDialog.Builder(a).setTitle("删除此单词？").setNegativeButton("保留",null).setPositiveButton("删除",(d,which)->{a.book.deleteWord(word.optString("id"));wordList();}).show());}a.button("返回单词本",this::wordList);});}
    float speechRate(){String rate=a.book.state("speech_rate","1.0");return rate.equals("0.7")?.7f:rate.equals("1.2")?1.2f:1f;}
    void speak(String word){if(speech==null){speech=new TextToSpeech(a,status->{if(status==TextToSpeech.SUCCESS){int result=speech.setLanguage(Locale.US);speechReady=result!=TextToSpeech.LANG_MISSING_DATA&&result!=TextToSpeech.LANG_NOT_SUPPORTED;if(speechReady){speech.setSpeechRate(speechRate());speech.speak(word,TextToSpeech.QUEUE_FLUSH,null,CloudApi.id());}else a.status("请先在手机系统安装英语语音。");}else a.status("此设备暂时无法使用语音。");});}else if(speechReady){speech.setSpeechRate(speechRate());speech.speak(word,TextToSpeech.QUEUE_FLUSH,null,CloudApi.id());}else a.status("英语语音尚未准备好。");}
    void startWords(boolean spelling) throws Exception {
        JSONArray words=filteredWords(),ids=new JSONArray();if(words.length()==0)throw new IOException("当前范围没有单词，请调整筛选或添加单词。");for(int i=0;i<words.length();i++)ids.put(words.getJSONObject(i).getString("id"));a.book.putState("word_session",new JSONObject().put("ids",ids).put("index",0).put("spelling",spelling).put("answer","").put("revealed",false).toString());resumeWords();
    }
    void resumeWords() throws Exception {JSONObject p=new JSONObject(a.book.state("word_session","{}"));wordStudy(p.getBoolean("spelling"),p.getInt("index"),p.optBoolean("revealed"));}
    void wordStudy(boolean spelling,int index,boolean revealed) throws Exception {
        JSONObject progress=new JSONObject(a.book.state("word_session","{}"));JSONArray order=progress.getJSONArray("ids"),words=a.book.words();if(index>=order.length()){a.book.putState("word_session","");wordList();a.status("本轮学习完成。");return;}
        JSONObject selected=null;for(int i=0;i<words.length();i++)if(words.getJSONObject(i).getString("id").equals(order.getString(index)))selected=words.getJSONObject(i);if(selected==null){progress.put("index",index+1).put("answer","").put("revealed",false);a.book.putState("word_session",progress.toString());resumeWords();return;}final JSONObject w=selected;
        page((spelling?"拼写":"翻卡")+" "+(index+1)+" / "+order.length(),"按自己的掌握情况安排复习，进度自动保存。",this::wordList);a.ui.studyProgress(index,order.length());
        if(spelling){a.text(w.optString("meaning"),22,true);EditText answer=field("拼写这个单词",progress.optString("answer"),false);watch(answer,()->safe(()->{progress.put("answer",answer.getText().toString());a.book.putState("word_session",progress.toString());}));a.button("检查拼写",()->safe(()->{progress.put("revealed",true).put("answer",answer.getText().toString());a.book.putState("word_session",progress.toString());resumeWords();}));if(revealed){a.text(progress.optString("answer").trim().equalsIgnoreCase(w.optString("word"))?"拼写正确":"正确拼写："+w.optString("word"),18,true);a.text(w.optString("phonetic")+"\n"+w.optString("example"),16,false);}}
        else {LinearLayout card=a.ui.card(PhoneUi.SURFACE);a.ui.space(card,20);TextView word=a.ui.label(w.getString("word"),getCompactWidth()?28:34,PhoneUi.TEXT,true);word.setGravity(Gravity.CENTER);card.addView(word);if(!w.optString("phonetic").isEmpty()){a.ui.space(card,10);TextView phonetic=a.ui.label(w.optString("phonetic"),16,PhoneUi.MUTED,false);phonetic.setGravity(Gravity.CENTER);card.addView(phonetic);}a.ui.space(card,24);if(!revealed)a.primary("翻开释义",()->safe(()->{progress.put("revealed",true);a.book.putState("word_session",progress.toString());resumeWords();}));if(revealed){a.ui.section("释义","");LinearLayout meaning=a.ui.card(PhoneUi.SURFACE);meaning.addView(a.ui.label(w.optString("meaning"),20,PhoneUi.TEXT,true));if(!w.optString("example").isEmpty()){a.ui.space(meaning,16);TextView example=a.ui.label(w.optString("example"),16,PhoneUi.MUTED,false);example.setLineSpacing(a.dp(4),1);meaning.addView(example);}}}
        a.button("朗读",()->speak(w.optString("word")));if(revealed){a.ui.section("这个单词，你记住了吗？","");for(String mastery:new String[]{"unknown","unsure","mastered"})a.button(masteryLabel(mastery)+" · 下一词",()->safe(()->{JSONObject next=Notebook.copy(progress).put("index",index+1).put("answer","").put("revealed",false);a.book.db.beginTransaction();try{a.book.reviewWord(w.getString("id"),mastery,days(mastery));a.book.putState("word_session",next.toString());a.book.db.setTransactionSuccessful();}finally{a.book.db.endTransaction();}resumeWords();}));}a.button("返回单词本",this::wordList);
    }
    void wordAI(){
        page("AI 补全单词","每行一个词；生成后核对释义和例句，再保存到单词本。",this::wordList);
        EditText input=field("待补全单词",a.book.state("word_ai_input",""),true);watch(input,()->a.book.putState("word_ai_input",input.getText().toString()));
        if(!a.book.state("word_ai_result","").isEmpty())a.ui.row("继续核对上次结果","上次生成内容保存在这个题库中","draft",()->wordReview(a.book.state("word_ai_result","")));
        a.primary("生成释义和例句",()->safe(()->{Notebook owner=a.book;JSONObject profile=ModelProfile.read(a,owner.uid);String text=input.getText().toString().trim();if(text.isEmpty())throw new IOException("请先填写要补全的单词。");if(text.split("\\r?\\n").length>200)throw new IOException("每次最多补全 200 个单词。");
            a.run(()->ask(profile,"你是中文英语学习助手，只返回 JSON：{\"words\":[{\"word\":\"原单词\",\"meaning\":\"词性与中文释义\",\"phonetic\":\"IPA\",\"example\":\"英文例句及中文译文\"}]}。保持输入词形，每个输入一项。不可靠的音标填空。",text,null),result->{String raw=(String)result;owner.putState("word_ai_result",raw);wordReview(raw);});}));
        a.button("返回单词本",this::wordList);
    }
    void wordReview(String raw){
        final JSONArray words;try{words=AiClient.words(raw);}catch(Exception invalid){page("单词补全未完成","返回内容不完整或格式有误，没有保存为单词。原结果与输入已保留，可以返回后手动重试。",this::wordAI);a.button("查看原始响应",()->new AlertDialog.Builder(a).setTitle("原始响应").setMessage(raw).setPositiveButton("关闭",null).show());a.primary("返回重新补全",this::wordAI);return;}
        page("核对单词补全","共 "+words.length()+" 个单词；可修改各项内容，确认后保存。",this::wordAI);
        for(int i=0;i<words.length();i++){JSONObject w=words.optJSONObject(i);a.ui.section("单词 "+(i+1),"");String[] keys={"word","meaning","phonetic","example"},labels={"单词","中文释义","音标","例句与译文"};int[] limits={300,2000,300,4000};for(int k=0;k<keys.length;k++){String key=keys[k];EditText e=field(labels[k],w.optString(key),k==1||k==3);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(limits[k])});watch(e,()->safe(()->{w.put(key,e.getText().toString());a.book.putState("word_ai_result",new JSONObject().put("words",words).toString());}));}}
        a.primary("核对并保存",()->safe(()->{JSONArray checked=AiClient.words(new JSONObject().put("words",words).toString());a.book.db.beginTransaction();try{for(int i=0;i<checked.length();i++){JSONObject w=checked.getJSONObject(i);a.book.word(null,w.getString("word"),w.getString("meaning"),w.getString("phonetic"),w.getString("example"));}a.book.putState("word_ai_result","");a.book.db.setTransactionSuccessful();}finally{a.book.db.endTransaction();}wordList();a.status("已保存 "+checked.length()+" 个单词。");}));a.button("返回单词本",this::wordList);
    }
    void account(){safe(()->{page("账号与同步",workspaceName()+"\n同一个账号，在手机和电脑继续学习。",this::mine);a.primary(a.api==null?"登录账号":"重新登录／切换账号",a::loginPage);if(a.api!=null)a.text("已登录："+a.api.username,17,true);
        a.button("同步题目、原图与掌握状态",()->{if(a.api==null){a.status("请先登录这个题库所属的账号。已保存的本机内容会保留。");return;}Notebook owner=a.book;CloudApi client=a.api;a.run(()->NotebookSync.synchronize(owner,client),result->{account();a.status((String)result);});});a.button("查看同步冲突",()->library("","","conflict"));
        a.text("最近同步："+a.book.state("last_sync","尚未同步"),14,false);
        if(!a.book.uid.equals("LOCAL"))a.button("导入本机空间的题目",()->new AlertDialog.Builder(a).setTitle("复制本机题目到此账号？").setMessage("会先备份账号题库，复制题目和原图，重复导入会跳过。本机空间的原数据保留；点击同步后才上传。").setNegativeButton("暂不导入",null).setPositiveButton("导入",(dialog,which)->{Notebook target=a.book;a.run(()->importLocal(target),result->{account();a.status("已导入 "+result+" 道题目。同步后两端可查看。");});}).show());
        a.button("发送照片给电脑（可选）",a::queuePage);
        if(!a.book.uid.equals("LOCAL"))a.button("退出账号，回到本机空间",()->safe(()->{if(a.api!=null)a.api.close();a.api=null;a.getPreferences(0).edit().remove("offline_uid").apply();a.openWorkspace("LOCAL");a.home();}));a.button("返回首页",a::home);
    });}
    int importLocal(Notebook target) throws Exception {
        Notebook source=new Notebook(new File(new File(a.getFilesDir(),"local"),"LOCAL"),"LOCAL");try{return importLocal(target,source);}finally{source.close();}
    }
    static int importLocal(Notebook target,Notebook source) throws Exception {
        if(!source.uid.equals("LOCAL")||target.uid.equals("LOCAL"))throw new IOException("请选择账号题库接收本机题目。");
            File folder=new File(target.root,"backups");folder.mkdirs();try(OutputStream out=new FileOutputStream(new File(folder,"before-import-"+CloudApi.id()+".zip"))){NotebookBackup.export(target,out);}int count=0;
            target.db.beginTransaction();try{for(JSONObject row:source.entries("","","")){String sid=row.getString("id");try(android.database.Cursor c=target.db.rawQuery("SELECT 1 FROM imports WHERE source_id=?",new String[]{sid})){if(c.moveToFirst())continue;}
                String id=CloudApi.id();JSONObject p=row.getJSONObject("payload");JSONArray images=new JSONArray(),originals=p.getJSONArray("attachments");for(int i=0;i<originals.length();i++){JSONObject image=originals.getJSONObject(i);String key=image.getString("key"),ext=key.substring(key.lastIndexOf('.')+1);images.put(target.addImage(CloudApi.read(source.file(image),CloudApi.MAX_IMAGE),ext,image.getString("original_name"),id));}target.save(id,p.getJSONObject("question"),images);JSONObject local=target.entry(id);local.getJSONObject("payload").put("review",p.get("review"));target.mutate(id,local.getJSONObject("payload"),false);target.db.execSQL("INSERT INTO imports VALUES(?,?)",new Object[]{sid,id});count++;}target.db.setTransactionSuccessful();}finally{target.db.endTransaction();}return count;
    }
    void modelSettings(){safe(()->{JSONObject p=ModelProfile.read(a,a.book.uid);page("手机识题模型","选择 DeepSeek 网页版或自定义模型接口，在手机直接识题，无需电脑在线。登录凭据与密钥在本机加密保存，不随题库同步或备份。",this::settings);
        a.text("当前接入："+(p.optString("provider").equals("deepseek_web")?"DeepSeek 网页版 · 手机本机":"自定义模型接口"),16,true);a.button("DeepSeek 网页版（手机本机）",this::webModelSettings);
        EditText url=field("接口完整地址（HTTPS）",p.optString("url"),false);url.setHint("https://服务地址/v1/chat/completions");EditText model=field("模型名称",p.optString("model"),false);a.text("API Key（留空保留原密钥）",14,true);EditText key=a.edit("输入新的 API Key",true);CheckBox clear=new CheckBox(a);clear.setText("清除已保存的密钥");a.page.addView(clear);a.button("保存并使用自定义接口",()->safe(()->{String secret=clear.isChecked()?"":key.getText().toString().isEmpty()?p.optString("key"):key.getText().toString();ModelProfile.write(a,a.book.uid,Notebook.copy(p).put("provider","compatible").put("url",url.getText().toString().trim()).put("model",model.getText().toString().trim()).put("key",secret));key.setText("");settings();a.status("模型设置已保存。识题仅在手动点击时请求。");}));a.button("返回设置",this::settings);
    });}
    void webModelSettings(){safe(()->{JSONObject profile=ModelProfile.read(a,a.book.uid);page("DeepSeek 网页版 · 手机本机","直接使用自己的网页账号；不需要电脑、API Key 或另部署反代服务。非官方接入可能因接口变化或账号限制失效。只在点击识题或补全时发起请求，失败不自动重试。",this::modelSettings);
        a.text(profile.optString("web_token").isEmpty()?"尚未配置网页登录":"此空间已保存加密网页登录，可重新登录更新。",15,true);a.button("在手机登录 DeepSeek",this::webLoginPage);
        a.text("也可填写自己的网页登录 Token（不是 API Key）",14,true);EditText secret=a.edit("网页登录 Token；留空保留已有登录",true);secret.setFilters(new InputFilter[]{new InputFilter.LengthFilter(16384)});
        a.button("保存并启用网页版",()->safe(()->{String value=secret.getText().toString().trim();if(value.isEmpty())value=profile.optString("web_token");String verified=DeepSeekWeb.token(value);ModelProfile.write(a,a.book.uid,Notebook.copy(profile).put("provider","deepseek_web").put("web_token",verified));secret.setText("");modelSettings();a.status("已启用手机本机网页版接入。识题仍需核对后收录。");}));
        a.button("清除网页版登录",()->safe(()->{profile.remove("web_token");if(profile.optString("provider").equals("deepseek_web"))profile.put("provider","compatible");ModelProfile.write(a,a.book.uid,profile);DeepSeekLogin.clear();webModelSettings();a.status("已清除此空间的网页登录；题库与草稿保留。");}));a.button("返回模型设置",this::modelSettings);
    });}
    void webLoginPage(){page("登录自己的 DeepSeek 账号","下方为 DeepSeek 官方网页。完成登录后点击使用；应用不记录网页登录密码。网页登录凭据只加密保存在此手机空间，不进入云同步和备份。",this::webModelSettings);webLogin=new DeepSeekLogin(a);a.page.addView(webLogin,new LinearLayout.LayoutParams(-1,a.dp(480)));
        a.button("我已登录，使用此账号",()->{DeepSeekLogin login=webLogin;String workspace=a.book.uid;login.capture(value->{if(webLogin!=login||!a.book.uid.equals(workspace))return;if(value.isEmpty()){a.status("尚未检测到网页登录。请完成登录后再点击，或返回填写自己的网页登录 Token。");return;}safe(()->{JSONObject p=ModelProfile.read(a,workspace);ModelProfile.write(a,workspace,p.put("provider","deepseek_web").put("web_token",value));webModelSettings();a.status("已保存加密网页登录，退出网页后可直接识题。");});});});a.button("取消登录",this::webModelSettings);
    }
    void settings(){page("设置与备份","管理识题服务、复习安排与自己的数据。",this::mine);a.ui.section("学习偏好","");a.ui.row("每日练习目标",goal()+" 次题目练习","stats",()->goalSettings(this::settings));a.ui.row("英语朗读语速",speechRate()==.7f?"慢速":speechRate()==1.2f?"快速":"标准","words",()->new AlertDialog.Builder(a).setTitle("英语朗读语速").setSingleChoiceItems(new String[]{"慢速","标准","快速"},speechRate()==.7f?0:speechRate()==1.2f?2:1,(d,w)->{a.book.putState("speech_rate",new String[]{"0.7","1.0","1.2"}[w]);d.dismiss();settings();}).setNegativeButton("取消",null).show());a.ui.row("手机识题模型","DeepSeek 网页版或自定义模型接口","settings",this::modelSettings);a.ui.row("复习间隔","按掌握程度调整下次复习时间","check",()->{page("复习间隔","单位：天，范围 0～365。新设置用于后续作答记录。",this::settings);Map<String,EditText> edits=new LinkedHashMap<>();for(String m:new String[]{"unknown","unsure","mastered"}){EditText e=field(masteryLabel(m),Integer.toString(days(m)),false);e.setInputType(InputType.TYPE_CLASS_NUMBER);edits.put(m,e);}a.button("保存复习设置",()->safe(()->{Map<String,Integer> values=new LinkedHashMap<>();for(Map.Entry<String,EditText> e:edits.entrySet()){int days=Integer.parseInt(e.getValue().getText().toString());if(days<0||days>365)throw new IOException("复习间隔为 0～365 天。");values.put(e.getKey(),days);}a.book.db.beginTransaction();try{for(Map.Entry<String,Integer> e:values.entrySet())a.book.putState("days_"+e.getKey(),e.getValue().toString());a.book.db.setTransactionSuccessful();}finally{a.book.db.endTransaction();}settings();}));a.button("返回设置",this::settings);});
        a.ui.section("数据与备份","");a.ui.row("导出手机题库备份 ZIP","保存题目、原图、草稿与学习记录","backup",()->{a.book.putState("backup_copy","");choose(BACKUP_SAVE,"application/zip",true);});a.ui.row("恢复手机备份 ZIP","恢复前会保留一份当前题库备份","backup",()->new AlertDialog.Builder(a).setTitle("从手机备份恢复？").setMessage("只接受此本机空间或同一账号的手机备份。恢复会替换当前题库，并先保存一份恢复前备份。电脑 ZIP 请先在电脑恢复再同步。").setNegativeButton("取消",null).setPositiveButton("选择备份",(d,w)->choose(BACKUP_OPEN,"application/zip",false)).show());
        a.ui.row("导入题目 JSON／CSV","导入电脑或其他来源的题目文件","library",()->choose(JSON_OPEN,"*/*",false));a.ui.row("查看恢复前备份","保留的数据副本可另存到手机文件","draft",this::recoveryBackups);}
    void recoveryBackups(){page("恢复前备份","自动保存的恢复前和导入前备份，可另存到手机文件。",this::settings);File folder=new File(a.book.root,"backups");File[] files=folder.listFiles();if(files==null||files.length==0)a.text("尚无恢复前备份。",16,false);else for(File f:files)if(f.isFile()&&f.getName().matches("(?:before-restore|before-import)-[a-f0-9]{32}\\.zip"))a.button(f.getName(),()->{a.book.putState("backup_copy",f.getName());choose(BACKUP_SAVE,"application/zip",true);});a.button("返回设置",this::settings);}
    void choose(int code,String mime,boolean create){try{Intent intent=new Intent(create?Intent.ACTION_CREATE_DOCUMENT:Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(mime);if(create)intent.putExtra(Intent.EXTRA_TITLE,code==JSON_SAVE?"Flandre-questions.json":code==CSV_SAVE?"Flandre-questions.csv":"Flandre-phone-backup.zip");a.startActivityForResult(intent,code);}catch(ActivityNotFoundException error){a.status("此设备没有可用文件选择器。");}}
    void exportJson() throws Exception {JSONArray questions=new JSONArray();for(JSONObject e:libraryRows())questions.put(e.getJSONObject("payload").getJSONObject("question"));String json=new JSONObject().put("questions",questions).toString();if(json.getBytes(StandardCharsets.UTF_8).length>8*1024*1024)throw new IOException("JSON 文本超过 8 MB，请缩小导出范围。");a.book.putState("json_export",json);choose(JSON_SAVE,"application/json",true);}
    void exportCsv() throws Exception {JSONArray qs=new JSONArray();for(JSONObject e:libraryRows())qs.put(e.getJSONObject("payload").getJSONObject("question"));String data=QuestionFiles.export(qs);if(data.getBytes(StandardCharsets.UTF_8).length>8*1024*1024)throw new IOException("CSV 超过 8 MB，请缩小导出范围。");a.book.putState("csv_export",data);choose(CSV_SAVE,"text/csv",true);}
    boolean result(int request,int result,Intent data){if(request<20||request>25)return false;if(result!=Activity.RESULT_OK||data==null||data.getData()==null)return true;Uri uri=data.getData();Notebook owner=a.book;a.run(()->{
        if(request==BACKUP_SAVE||request==JSON_SAVE||request==CSV_SAVE){try(OutputStream out=a.getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("无法写入这个位置。");if(request==JSON_SAVE||request==CSV_SAVE)out.write(owner.state(request==JSON_SAVE?"json_export":"csv_export","{}").getBytes(StandardCharsets.UTF_8));else{String copy=owner.state("backup_copy","");if(copy.isEmpty())NotebookBackup.export(owner,out);else{if(!copy.matches("(?:before-restore|before-import)-[a-f0-9]{32}\\.zip"))throw new IOException("备份编号无效。");try(InputStream in=new FileInputStream(new File(new File(owner.root,"backups"),copy))){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);}owner.putState("backup_copy","");}}}return "已导出文件。";}
        try(InputStream in=a.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取所选文件。");if(request==BACKUP_OPEN){NotebookBackup.restore(owner,in);return "备份已恢复，恢复前备份保留在本机。";}String text=new String(NotebookBackup.read(in,8*1024*1024),StandardCharsets.UTF_8);if(request==WORDS_OPEN){String[] lines=text.replace("\r","").split("\n");if(lines.length>20000)throw new IOException("单词过多。");owner.db.beginTransaction();try{int count=0;for(String line:lines){String word=line.trim();if(word.isEmpty())continue;String[] pair=word.split("\t",2);owner.word(null,pair[0],pair.length>1?pair[1]:"","","");count++;}owner.db.setTransactionSuccessful();return "已导入 "+count+" 个词。";}finally{owner.db.endTransaction();}}
            JSONArray qs=QuestionFiles.questions(text);if(qs.length()>20000)throw new IOException("题目过多。");int count=0;Set<String> known=new HashSet<>();for(JSONObject e:owner.entries("","",""))known.add(Notebook.question(e.getJSONObject("payload").getJSONObject("question")).toString());owner.db.beginTransaction();try{for(int i=0;i<qs.length();i++){JSONObject question=Notebook.question(qs.getJSONObject(i));if(known.add(question.toString())){owner.save(null,question,null);count++;}}owner.db.setTransactionSuccessful();return "已导入 "+count+" 道题，重复内容已跳过。";}finally{owner.db.endTransaction();}}
    },value->{settings();a.status((String)value);});return true;}
}
