package com.flandre.notebook;

import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.Build;
import android.text.TextUtils;
import android.view.*;
import android.widget.*;

/** Shared native surfaces. No UI framework or remote visual assets. */
final class PhoneUi {
    static final int BG=0xfff7f5f4,SURFACE=Color.WHITE,TEXT=0xff302938,MUTED=0xff756d7e,ACCENT=0xffac456d,SOFT=0xfff8eaf0,LINE=0xffeae5ed;
    final MainActivity a;LinearLayout root,bar,nav,notice;TextView message;ProgressBar progress;View back;ScrollView scroll;boolean ime=false;String selected="";
    PhoneUi(MainActivity activity){a=activity;}
    int d(int n){return a.dp(n);}
    TextView label(String value,int size,int color,boolean bold){TextView t=new TextView(a);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");if(bold)t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));return t;}
    GradientDrawable shape(int color,int radius,boolean border){GradientDrawable bg=new GradientDrawable();bg.setColor(color);bg.setCornerRadius(d(radius));if(border)bg.setStroke(d(1),LINE);return bg;}
    Drawable ripple(int color,int radius,boolean border){return new RippleDrawable(ColorStateList.valueOf(0x22ac456d),shape(color,radius,border),shape(Color.WHITE,radius,false));}
    LinearLayout vertical(){LinearLayout v=new LinearLayout(a);v.setOrientation(LinearLayout.VERTICAL);return v;}
    void space(LinearLayout parent,int height){View v=new View(a);parent.addView(v,new LinearLayout.LayoutParams(1,d(height)));}
    void screen(String title,String hint){
        if(root!=null)root.setOnApplyWindowInsetsListener(null);
        selected="";root=vertical();root.setBackgroundColor(BG);bar=new LinearLayout(a);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(d(12),d(8),d(16),d(8));
        FrameLayout backBox=new FrameLayout(a);backBox.setBackground(ripple(BG,14,false));backBox.setContentDescription("返回上一页");backBox.setFocusable(true);Icon arrow=new Icon("back",TEXT);FrameLayout.LayoutParams arrowParams=new FrameLayout.LayoutParams(d(22),d(22),Gravity.CENTER);backBox.addView(arrow,arrowParams);backBox.setOnClickListener(v->{if(!a.busy)a.handleBack();});bar.addView(backBox,new LinearLayout.LayoutParams(d(48),d(48)));back=backBox;
        TextView name=label(title,20,TEXT,true);name.setMaxLines(2);name.setEllipsize(TextUtils.TruncateAt.END);LinearLayout.LayoutParams heading=new LinearLayout.LayoutParams(0,-2,1);heading.leftMargin=d(6);bar.addView(name,heading);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));
        notice=new LinearLayout(a);notice.setGravity(Gravity.CENTER_VERTICAL);notice.setPadding(d(16),d(10),d(16),d(10));notice.setBackground(shape(SOFT,12,false));progress=new ProgressBar(a);progress.setIndeterminateTintList(ColorStateList.valueOf(ACCENT));LinearLayout.LayoutParams spinner=new LinearLayout.LayoutParams(d(20),d(20));spinner.rightMargin=d(10);notice.addView(progress,spinner);message=label("",13,ACCENT,false);message.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);notice.addView(message,new LinearLayout.LayoutParams(0,-2,1));notice.setVisibility(View.GONE);LinearLayout.LayoutParams banner=new LinearLayout.LayoutParams(-1,-2);banner.setMargins(d(20),0,d(20),d(8));root.addView(notice,banner);
        scroll=new ScrollView(a);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false);a.page=vertical();a.page.setPadding(d(20),d(6),d(20),d(24));scroll.addView(a.page,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));if(hint!=null&&!hint.trim().isEmpty()){TextView subtitle=label(hint,14,MUTED,false);subtitle.setLineSpacing(d(3),1);a.page.addView(subtitle);space(a.page,14);}
        nav=new LinearLayout(a);nav.setGravity(Gravity.CENTER_VERTICAL);nav.setPadding(d(8),d(8),d(8),d(8));nav.setBackgroundColor(SURFACE);nav.setElevation(d(8));nav.setVisibility(View.GONE);root.addView(nav,new LinearLayout.LayoutParams(-1,-2));
        root.setOnApplyWindowInsetsListener((v,insets)->{int bottom=insets.getSystemWindowInsetBottom();ime=bottom>d(100);if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()),keyboard=insets.getInsets(WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,keyboard.bottom));ime=insets.isVisible(WindowInsets.Type.ime());}else v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),bottom);nav.setVisibility(selected.isEmpty()||ime?View.GONE:View.VISIBLE);return insets;});
        a.setContentView(root);root.requestApplyInsets();
    }
    void status(String value){message.setText(value);notice.setVisibility(value.isEmpty()?View.GONE:View.VISIBLE);progress.setVisibility(a.busy?View.VISIBLE:View.GONE);}
    void navigation(String active){selected=active;back.setVisibility(View.GONE);nav.removeAllViews();String[] keys={"home","library","capture","learn","mine"},names={"首页","题库","拍题","学习","我的"},icons={"home","library","plus","learn","person"};
        for(int i=0;i<keys.length;i++){final String key=keys[i];boolean chosen=key.equals(active);LinearLayout item=vertical();item.setGravity(Gravity.CENTER);item.setPadding(0,d(3),0,d(3));item.setMinimumHeight(d(56));item.setBackground(ripple(chosen?SOFT:SURFACE,14,false));Icon icon=new Icon(icons[i],chosen?ACCENT:MUTED);item.addView(icon,new LinearLayout.LayoutParams(d(24),d(24)));TextView text=label(names[i],12,chosen?ACCENT:MUTED,chosen);LinearLayout.LayoutParams t=new LinearLayout.LayoutParams(-2,-2);t.topMargin=d(4);item.addView(text,t);item.setContentDescription(names[i]+(chosen?"，当前页面":""));item.setFocusable(true);item.setSelected(chosen);item.setOnClickListener(v->{if(a.busy||key.equals(selected))return;if(key.equals("home"))a.home();else if(key.equals("library"))a.screens.library("","","");else if(key.equals("capture"))a.screens.captureHome();else if(key.equals("learn"))a.screens.practiceMenu();else a.screens.mine();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(d(3),0,d(3),0);nav.addView(item,p);}
        nav.setVisibility(ime?View.GONE:View.VISIBLE);
    }
    Button button(String title,Runnable action){Button b=new Button(a);b.setText(title);b.setTextSize(15);b.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));b.setAllCaps(false);b.setTextColor(TEXT);b.setMinHeight(d(52));b.setMinimumHeight(d(52));b.setGravity(Gravity.CENTER);b.setPadding(d(16),d(12),d(16),d(12));b.setBackground(ripple(SURFACE,14,true));b.setStateListAnimator(null);b.setOnClickListener(v->{if(!a.busy)action.run();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(10);a.page.addView(b,p);
        if(title.startsWith("返回")||title.startsWith("取消")||title.startsWith("稍后")){b.setTextColor(MUTED);b.setBackground(ripple(BG,14,false));}else if(title.startsWith("删除")||title.startsWith("舍弃")||title.startsWith("清除")){b.setTextColor(0xffb34251);b.setBackground(ripple(0xfffff0f2,14,false));}return b;
    }
    Button primary(String title,Runnable action){Button b=button(title,action);b.setTextColor(Color.WHITE);b.setBackground(ripple(ACCENT,14,false));return b;}
    EditText edit(String hint,boolean password){EditText e=new EditText(a);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setPadding(d(14),d(13),d(14),d(13));e.setMinHeight(d(52));GradientDrawable focused=shape(SURFACE,12,false);focused.setStroke(d(2),ACCENT);StateListDrawable states=new StateListDrawable();states.addState(new int[]{android.R.attr.state_focused},focused);states.addState(new int[0],shape(SURFACE,12,true));e.setBackground(states);if(password){e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);e.setSaveEnabled(false);e.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=d(4);a.page.addView(e,p);return e;}
    ArrayAdapter<String> choices(java.util.List<String> values){return new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,values){public View getView(int position,View reuse,ViewGroup parent){TextView t=(TextView)super.getView(position,reuse,parent);t.setTextSize(14);t.setTextColor(TEXT);t.setPadding(0,0,0,0);return t;}};}
    FrameLayout dropdown(Spinner spinner){FrameLayout box=new FrameLayout(a);box.setBackground(shape(SURFACE,12,true));spinner.setBackgroundColor(Color.TRANSPARENT);spinner.setPadding(d(10),0,d(30),0);box.addView(spinner,new FrameLayout.LayoutParams(-1,-1));Icon arrow=new Icon("down",MUTED);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(d(16),d(16),Gravity.RIGHT|Gravity.CENTER_VERTICAL);p.rightMargin=d(10);box.addView(arrow,p);return box;}
    void section(String title,String note){space(a.page,18);LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(label(title,18,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));if(!note.isEmpty())row.addView(label(note,12,MUTED,false));a.page.addView(row);space(a.page,8);}
    LinearLayout card(int color){LinearLayout v=vertical();v.setPadding(d(18),d(18),d(18),d(18));v.setBackground(shape(color,20,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(10);a.page.addView(v,p);return v;}
    void studyHero(int done,int goal,String caption,Runnable settings){LinearLayout card=card(TEXT);GradientDrawable gradient=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff463447,0xff29252f});gradient.setCornerRadius(d(24));card.setBackground(gradient);card.addView(label(caption,12,0xffe2cdd8,false));space(card,18);LinearLayout line=new LinearLayout(a);line.setGravity(Gravity.CENTER_VERTICAL);LinearLayout copy=vertical();copy.addView(label(a.getResources().getConfiguration().screenWidthDp<360?"每天进步一点":"今天，也进步一点。",a.getResources().getConfiguration().screenWidthDp<360?20:23,Color.WHITE,true));space(copy,8);copy.addView(label("今日已完成 "+done+" 次题目练习",13,0xffe2cdd8,false));line.addView(copy,new LinearLayout.LayoutParams(0,-2,1));View ring=new View(a){final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);protected void onDraw(Canvas c){float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(cx,cy)-d(6);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(d(5));paint.setStrokeCap(Paint.Cap.ROUND);paint.setColor(0xff665565);c.drawCircle(cx,cy,r,paint);paint.setColor(0xffefb5cd);c.drawArc(cx-r,cy-r,cx+r,cy+r,-90,360*Math.min(1f,done/(float)goal),false,paint);paint.setStyle(Paint.Style.FILL);paint.setColor(Color.WHITE);paint.setTypeface(Typeface.create("sans-serif-medium",0));paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(d(18));c.drawText(Math.round(Math.min(1f,done/(float)goal)*100)+"%",cx,cy+d(6),paint);}};ring.setContentDescription("今日目标 "+goal+" 次，已完成 "+done+" 次");line.addView(ring,new LinearLayout.LayoutParams(d(76),d(76)));card.addView(line);space(card,14);TextView goalText=label("每日目标 "+goal+" 次  ·  调整目标  ›",12,0xffefb5cd,true);goalText.setMinHeight(d(48));goalText.setGravity(Gravity.CENTER_VERTICAL);goalText.setBackground(ripple(0x00302938,12,false));goalText.setFocusable(true);goalText.setOnClickListener(v->{if(!a.busy)settings.run();});card.addView(goalText);}
    void studyProgress(int done,int total){ProgressBar v=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);v.setMax(Math.max(1,total));v.setProgress(Math.min(done,total));v.setProgressTintList(ColorStateList.valueOf(ACCENT));v.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));v.setContentDescription("进度 "+done+" / "+total);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,d(6));p.setMargins(0,d(6),0,d(18));a.page.addView(v,p);}
    void toggle(CompoundButton b){b.setTextColor(TEXT);b.setTextSize(15);b.setMinHeight(d(52));b.setPadding(d(12),d(8),d(12),d(8));b.setButtonTintList(ColorStateList.valueOf(ACCENT));b.setBackground(ripple(SURFACE,14,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(8);b.setLayoutParams(p);}
    void weekChart(String[] names,int[] values){LinearLayout card=card(SURFACE);card.addView(label("近 7 天练习",17,TEXT,true));StringBuilder description=new StringBuilder();for(int i=0;i<7;i++)description.append(names[i]).append("，").append(values[i]).append(" 次；");View chart=new View(a){final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);protected void onDraw(Canvas c){int maximum=1;for(int value:values)maximum=Math.max(maximum,value);float cell=getWidth()/7f,top=d(26),base=getHeight()-d(28);p.setTypeface(Typeface.create("sans-serif",0));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(d(11));for(int i=0;i<7;i++){float x=cell*(i+.5f),h=(base-top)*values[i]/maximum;p.setColor(i==6?ACCENT:0xffdbb8c7);c.drawRoundRect(x-d(10),base-Math.max(d(3),h),x+d(10),base,d(5),d(5),p);p.setColor(MUTED);c.drawText(Integer.toString(values[i]),x,base-h-d(8),p);c.drawText(names[i],x,base+d(21),p);}}};chart.setContentDescription(description.toString());card.addView(chart,new LinearLayout.LayoutParams(-1,d(170)));}
    void metrics(String[] values,String[] names){LinearLayout row=new LinearLayout(a);for(int i=0;i<values.length;i++){LinearLayout cell=vertical();cell.setPadding(d(12),d(16),d(8),d(16));cell.setBackground(shape(SURFACE,16,false));cell.addView(label(values[i],26,i==1?ACCENT:TEXT,true));space(cell,3);cell.addView(label(names[i],12,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);if(i>0)p.leftMargin=d(8);row.addView(cell,p);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(12);a.page.addView(row,p);}
    void shortcuts(String[] titles,String[] icons,Runnable[] actions){LinearLayout line=new LinearLayout(a);for(int i=0;i<titles.length;i++){final Runnable action=actions[i];LinearLayout item=vertical();item.setGravity(Gravity.CENTER);item.setPadding(d(4),d(16),d(4),d(16));item.setBackground(ripple(SURFACE,16,false));item.addView(new Icon(icons[i],ACCENT),new LinearLayout.LayoutParams(d(25),d(25)));space(item,10);TextView title=label(titles[i],13,TEXT,true);title.setGravity(Gravity.CENTER);item.addView(title);item.setFocusable(true);item.setContentDescription(titles[i]);item.setOnClickListener(v->{if(!a.busy)action.run();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);if(i>0)p.leftMargin=d(10);line.addView(item,p);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(10);a.page.addView(line,p);}
    void row(String title,String subtitle,String icon,Runnable action){row(title,subtitle,icon,action,SURFACE);}
    void row(String title,String subtitle,String icon,Runnable action,int color){LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(d(14),d(15),d(14),d(15));row.setMinimumHeight(d(72));row.setBackground(ripple(color,16,false));FrameLayout badge=new FrameLayout(a);badge.setBackground(shape(SOFT,12,false));badge.addView(new Icon(icon,ACCENT),new FrameLayout.LayoutParams(d(23),d(23),Gravity.CENTER));row.addView(badge,new LinearLayout.LayoutParams(d(44),d(44)));LinearLayout copy=vertical();TextView name=label(title,16,TEXT,true);name.setMaxLines(2);name.setEllipsize(TextUtils.TruncateAt.END);copy.addView(name);if(!subtitle.isEmpty()){TextView hint=label(subtitle,13,MUTED,false);hint.setMaxLines(2);hint.setEllipsize(TextUtils.TruncateAt.END);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(5);copy.addView(hint,p);}LinearLayout.LayoutParams content=new LinearLayout.LayoutParams(0,-2,1);content.setMargins(d(12),0,d(8),0);row.addView(copy,content);row.addView(new Icon("next",MUTED),new LinearLayout.LayoutParams(d(18),d(18)));row.setFocusable(true);row.setContentDescription(title+(subtitle.isEmpty()?"":"，"+subtitle));row.setOnClickListener(v->{if(!a.busy)action.run();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=d(8);a.page.addView(row,p);}
    void empty(String title,String hint,String icon){LinearLayout box=card(SURFACE);box.setGravity(Gravity.CENTER);box.addView(new Icon(icon,ACCENT),new LinearLayout.LayoutParams(d(42),d(42)));space(box,14);box.addView(label(title,17,TEXT,true));TextView note=label(hint,14,MUTED,false);note.setGravity(Gravity.CENTER);note.setLineSpacing(d(3),1);space(box,8);box.addView(note);}
    void question(String tags,String stem,Runnable action){LinearLayout card=card(SURFACE);card.setBackground(ripple(SURFACE,18,false));TextView label=label(tags,12,ACCENT,true);card.addView(label);space(card,9);TextView body=label(stem,16,TEXT,true);body.setMaxLines(4);body.setEllipsize(TextUtils.TruncateAt.END);body.setLineSpacing(d(3),1);card.addView(body);space(card,12);TextView footer=label("查看题目与解析  →",12,MUTED,false);card.addView(footer);card.setFocusable(true);card.setContentDescription(tags+"，"+stem);card.setOnClickListener(v->{if(!a.busy)action.run();});}
    final class Icon extends View {
        final String name;final int color;final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
        Icon(String type,int tint){super(a);name=type;color=tint;setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
        void line(Canvas c,float... points){Path path=new Path();path.moveTo(points[0],points[1]);for(int i=2;i<points.length;i+=2)path.lineTo(points[i],points[i+1]);c.drawPath(path,p);}
        protected void onDraw(Canvas c){super.onDraw(c);float size=Math.min(getWidth(),getHeight());c.save();c.translate((getWidth()-size)/2,(getHeight()-size)/2);c.scale(size/24,size/24);p.setColor(color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.7f);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);
            switch(name){case "home":line(c,3,11,12,3,21,11);line(c,5,10,5,21,10,21,10,15,14,15,14,21,19,21,19,10);break;case "library":case "book":c.drawRoundRect(4,3,20,21,2,2,p);line(c,8,3,8,21);line(c,11,8,17,8);line(c,11,12,16,12);break;case "camera":line(c,3,8,7,8,9,5,15,5,17,8,21,8,21,20,3,20,3,8);c.drawCircle(12,14,3.5f,p);break;case "plus":line(c,12,5,12,19);line(c,5,12,19,12);break;case "person":c.drawCircle(12,7,3.5f,p);c.drawArc(4,12,20,27,180,180,false,p);break;case "learn":line(c,3,9,12,4,21,9,12,14,3,9);line(c,6,11,6,17,12,20,18,17,18,11);break;case "image":c.drawRoundRect(3,4,21,20,2,2,p);c.drawCircle(8,9,1.5f,p);line(c,4,18,10,12,14,16,17,13,21,17);break;case "edit":line(c,4,20,5,15,16,4,20,8,9,19,4,20);line(c,13,7,17,11);break;case "stats":line(c,4,4,4,20,21,20);line(c,8,16,8,12);line(c,13,16,13,8);line(c,18,16,18,4);break;case "cloud":c.drawArc(2,10,12,22,90,180,false,p);c.drawArc(6,4,19,17,175,190,false,p);c.drawArc(14,10,23,22,270,180,false,p);line(c,7,21,18,21);break;case "words":line(c,3,5,11,5,13,7,15,5,21,5,21,21,15,21,12,19,9,21,3,21,3,5);line(c,12,8,12,18);break;case "settings":c.drawCircle(12,12,7,p);c.drawCircle(12,12,2.5f,p);for(int i=0;i<8;i++){double rad=i*Math.PI/4;line(c,(float)(12+7*Math.cos(rad)),(float)(12+7*Math.sin(rad)),(float)(12+10*Math.cos(rad)),(float)(12+10*Math.sin(rad)));}break;case "backup":c.drawRoundRect(3,7,21,21,2,2,p);line(c,3,11,21,11);line(c,8,4,16,4);line(c,9,15,15,15);break;case "check":line(c,5,12,10,17,19,7);break;case "draft":c.drawRoundRect(5,3,19,21,2,2,p);line(c,9,8,15,8);line(c,9,12,15,12);line(c,9,16,13,16);break;case "back":line(c,15,5,8,12,15,19);break;case "next":line(c,9,5,16,12,9,19);break;case "down":line(c,5,9,12,16,19,9);break;case "more":c.drawCircle(12,5,0.6f,p);c.drawCircle(12,12,0.6f,p);c.drawCircle(12,19,0.6f,p);break;default:c.drawCircle(12,12,8,p);line(c,12,7,12,13,16,13);}
            c.restore();
        }
    }
}
